apiVersion: conventions.apps.tanzu.vmware.com/v1alpha1
kind: PodIntent
metadata:
  name: podintent-test
spec:
  template:
    metadata:
      annotations:
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
    spec:
      containers:
        - image: ghcr.io/nginx-proxy/nginx-proxy:latest
          name: workload