apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: tanzu-system-ingress
spec:
  delegations:
    - secretName: demo-cl01-lespaulstudioplus-info
      targetNamespaces:
        - "*"
---
apiVersion: conventions.apps.tanzu.vmware.com/v1alpha1
kind: ClusterPodConvention
metadata:
  name: dumper
spec:
  priority: Early
  webhook:
    clientConfig:
      url: https://my-convention-default.demo.cl01.lespaulstudioplus.info/convention